name: smart_task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get: ^4.7.3
  flutter_secure_storage: ^10.0.0
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  internet_connection_checker: ^3.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  dartz: ^0.10.1
  intl: ^0.20.2
  shimmer: ^3.0.0


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  mocktail: ^1.0.0
   

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500 
